import React from 'react'
import '@/app/globals.css'

import HomeHeader from '@/components/headers/HomeHeader'
import Footer from '@/components/Footer'
import Header from '@/components/headers/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <div className="">
        {children}
      </div>
      <Footer />
    </>
  )
}
